//! Cache-dir layout and connection opening: the writer open (schema
//! init, WAL, busy handling) and the resilient read-only / read-write
//! reader opens that survive the WAL-checkpoint CANTOPEN window.

use super::*;

pub fn cache_base_dir() -> Option<PathBuf> {
    if let Ok(xdg) = std::env::var("XDG_CACHE_HOME") {
        if !xdg.is_empty() {
            return Some(PathBuf::from(xdg).join("perl-lsp"));
        }
    }
    if let Ok(home) = std::env::var("HOME") {
        return Some(PathBuf::from(home).join(".cache").join("perl-lsp"));
    }
    None
}

pub fn cache_dir_for_workspace(workspace_root: Option<&str>) -> Option<PathBuf> {
    let base = cache_base_dir()?;
    match workspace_root {
        Some(root) => {
            use std::collections::hash_map::DefaultHasher;
            use std::hash::{Hash, Hasher};
            let mut hasher = DefaultHasher::new();
            root.hash(&mut hasher);
            Some(base.join(format!("{:016x}", hasher.finish())))
        }
        None => Some(base),
    }
}

/// Per-language DB filename — Perl keeps `modules.db` (back-compat), every
/// pack language gets its own `modules-{lang}.db` so names never comingle on
/// disk (a Perl `Box` and a C++ class `Box` live in different files). The
/// ONE spelling both openers share.
pub fn db_path_for(dir: &std::path::Path, lang: &str) -> PathBuf {
    if lang == "perl" {
        dir.join("modules.db")
    } else {
        dir.join(format!("modules-{lang}.db"))
    }
}

#[cfg(not(test))]
pub fn open_cache_db(workspace_root: Option<&str>, lang: &str) -> Option<Connection> {
    let dir = cache_dir_for_workspace(workspace_root)?;
    open_cache_db_at(&dir, lang, WRITER_BUSY_TIMEOUT)
}

/// How long a writer waits on a busy DB before failing its statement. Two
/// writers share the Perl DB (resolver thread + workspace indexer), and a
/// failed commit after resident copies were stripped is unrecoverable for
/// the session — so waiting beats failing.
// Read by the production opener only; the test opener shortens the wait.
#[cfg_attr(test, allow(dead_code))]
pub(super) const WRITER_BUSY_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);

/// The writer open, given the cache directory: WAL, busy handling, schema
/// init, and the corruption-only recreate. Both the production opener and
/// the test override (`with_test_cache_dir`) route here, so a test drives
/// WAL plus the durability mode this cache actually wants.
///
/// `synchronous` defaults to FULL, which fsyncs the WAL on every commit — and
/// the bulk indexer commits once per ≤128-file chunk, so a cold index pays a
/// flush per chunk for data that is **entirely derived**. Every blob and row
/// here can be regenerated by re-parsing the file it came from, and the
/// generation stamps already detect a row that does not match its source.
/// NORMAL keeps the WAL crash-safe against a process dying (the case that
/// actually happens) and only risks the most recent commits on a machine-level
/// power loss — where the cost is re-indexing those files, not wrong answers.
///
/// One speller, because the recreate path below opens a second connection and
/// a pragma set on only one of them is the kind of drift nobody notices.
fn apply_pragmas(conn: &Connection, busy: std::time::Duration) {
    let sync = std::env::var("PERL_LSP_SQLITE_SYNC").unwrap_or_else(|_| "NORMAL".to_string());
    let _ = conn.execute_batch(&format!(
        "PRAGMA journal_mode=WAL; PRAGMA synchronous={sync};"
    ));
    // Two writers share the Perl DB (resolver thread + workspace indexer); a
    // busy writer must wait, not fail its txn — a failed commit after resident
    // copies were stripped is unrecoverable for the session.
    let _ = conn.busy_timeout(busy);
}

/// the real body rather than a parallel one.
pub(super) fn open_cache_db_at(
    dir: &std::path::Path,
    lang: &str,
    busy: std::time::Duration,
) -> Option<Connection> {
    std::fs::create_dir_all(dir).ok()?;
    let db_path = db_path_for(dir, lang);
    log::info!("Module cache: {:?}", db_path);

    match Connection::open(&db_path) {
        Ok(conn) => {
            apply_pragmas(&conn, busy);
            match init_schema(&conn) {
                Ok(()) => Some(conn),
                Err(e) => {
                    // BUSY/LOCKED is contention (a sibling writer mid-init,
                    // e.g. the one-time idx_modules_path build) — deleting
                    // the live DB under its feet loses every blob the other
                    // writer stripped against. Only recreate on real
                    // corruption/shape failures.
                    if matches!(
                        e.sqlite_error_code(),
                        Some(rusqlite::ErrorCode::DatabaseBusy)
                            | Some(rusqlite::ErrorCode::DatabaseLocked)
                    ) {
                        log::warn!("Cache DB busy during init; running without cache: {}", e);
                        return None;
                    }
                    log::warn!("Cache DB schema init failed: {}. Recreating.", e);
                    drop(conn);
                    let _ = std::fs::remove_file(&db_path);
                    let conn = Connection::open(&db_path).ok()?;
                    apply_pragmas(&conn, busy);
                    init_schema(&conn).ok()?;
                    Some(conn)
                }
            }
        }
        Err(e) => {
            log::warn!("Failed to open cache DB: {}", e);
            None
        }
    }
}

#[cfg(test)]
thread_local! {
    /// Opt-in real cache DB for the current test thread: `(dir, busy timeout)`.
    /// Unset — the default — keeps `open_cache_db` answering `None` exactly as
    /// a stubbed-out open always did, so no existing test changes behaviour.
    /// A test that needs the persist/strip lanes (whose whole point is a
    /// *committed blob*, and which are otherwise unreachable from `cargo test`)
    /// installs one with `with_test_cache_dir`.
    static TEST_CACHE_DIR: std::cell::RefCell<Option<(PathBuf, std::time::Duration)>> =
        const { std::cell::RefCell::new(None) };
}

// Used by the pack-language cache tests; a Perl-only test build has no caller.
#[allow(dead_code)]
/// Run `f` with `open_cache_db` backed by a real SQLite DB under `dir` on
/// THIS thread. Thread-local, so parallel tests can't see each other's; the
/// short busy timeout is what lets a test drive a *contended* writer without
/// waiting out the production `WRITER_BUSY_TIMEOUT`.
#[cfg(test)]
pub fn with_test_cache_dir<R>(dir: &std::path::Path, busy: std::time::Duration, f: impl FnOnce() -> R) -> R {
    struct Restore(Option<(PathBuf, std::time::Duration)>);
    impl Drop for Restore {
        fn drop(&mut self) {
            let prev = self.0.take();
            TEST_CACHE_DIR.with(|c| *c.borrow_mut() = prev);
        }
    }
    let prev = TEST_CACHE_DIR.with(|c| c.borrow_mut().replace((dir.to_path_buf(), busy)));
    let _restore = Restore(prev);
    f()
}

#[cfg(test)]
pub fn open_cache_db(_workspace_root: Option<&str>, lang: &str) -> Option<Connection> {
    let installed = TEST_CACHE_DIR.with(|c| c.borrow().clone());
    let (dir, busy) = installed?;
    open_cache_db_at(&dir, lang, busy)
}

/// Read-only open for query-path consumers (the relational retrieval, bag
/// rehydration): no schema init, no WAL pragma churn — the writer created
/// the schema. Returns `None` when the DB file doesn't exist yet (nothing
/// persisted → no candidates), or in tests.
#[cfg(not(test))]
pub fn open_cache_db_readonly(workspace_root: Option<&str>, lang: &str) -> Option<Connection> {
    let dir = cache_dir_for_workspace(workspace_root)?;
    open_cache_reader_at(&db_path_for(&dir, lang))
}

/// Resilient query-path reader open (`open_reader_retrying`): retries across
/// the transient CANTOPEN window a writer's WAL checkpoint opens instead of
/// returning an empty result.
/// Routing every reader — bag rehydration, the relational-ref reader, warm
/// streaming — through here keeps the writer's WAL-checkpoint window from
/// degrading their results to silent absence. `None` only when the window
/// never clears (DB absent / truly unreadable).
// Sole consumer is the real read-only opener above, `#[cfg(not(test))]` —
// match its cfg.
#[cfg(not(test))]
pub fn open_cache_reader_at(db_path: &std::path::Path) -> Option<Connection> {
    open_reader_retrying(db_path).ok()
}

/// Open the cache reader across the transient window a writer's WAL
/// checkpoint/reset opens. During it a fresh open of the WAL-mode DB (SQLite
/// setting up the `-wal`/`-shm` auxiliaries) returns `SQLITE_CANTOPEN` for
/// BOTH read-only and read-write modes — and
/// `busy_timeout` does NOT cover the open itself. Each attempt tries
/// read-only then read-write (a read-write open additionally recovers a WAL
/// a read-only open can't map); bounded backoff (~0.26 s total) waits the
/// window out. `Err` only when the window never clears — a genuinely
/// unreadable DB, a real invariant break the strict tripwire should catch.
pub fn open_reader_retrying(db_path: &std::path::Path) -> Result<Connection, String> {
    let mut delay = std::time::Duration::from_millis(2);
    let mut last = String::new();
    for attempt in 0..10 {
        match open_readonly_at(db_path) {
            Ok(c) => {
                if attempt > 0 {
                    log::warn!(
                        "cache reader open {db_path:?} recovered read-only after \
                         {attempt} retr{} (transient WAL-checkpoint CANTOPEN window)",
                        if attempt == 1 { "y" } else { "ies" }
                    );
                }
                return Ok(c);
            }
            Err(e) => last = e,
        }
        // Reaching here means the read-only open just failed; a read-write
        // open that succeeds recovered the transient window. Log even on
        // attempt 0 so an RW recovery is observable, never silent.
        if let Some(c) = open_rw_shared_at(db_path) {
            log::warn!(
                "cache reader open {db_path:?} recovered read-write on attempt \
                 {attempt} (read-only hit the transient CANTOPEN window)"
            );
            return Ok(c);
        }
        if attempt < 9 {
            std::thread::sleep(delay);
            delay = (delay * 2).min(std::time::Duration::from_millis(50));
        }
    }
    Err(last)
}

/// Read-only open of an explicit DB file. Path-taking so the rehydration
/// logic is unit-testable without the cache-dir plumbing.
pub fn open_readonly_at(db_path: &std::path::Path) -> Result<Connection, String> {
    let conn = Connection::open_with_flags(
        db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )
    .map_err(|e| format!("readonly open {db_path:?}: {e}"))?;
    let _ = conn.busy_timeout(std::time::Duration::from_secs(10));
    Ok(conn)
}

/// Read-WRITE open (no CREATE) of an explicit, already-persisted DB file —
/// the WAL-checkpoint recovery open. A fresh `SQLITE_OPEN_READ_ONLY` open of a
/// WAL-mode cache DB transiently fails with `SQLITE_CANTOPEN` while a
/// sibling writer is mid-`wal_checkpoint` (the -wal is being truncated and
/// the -shm reset; a read-only conn can't rebuild the wal-index in that
/// window). A read-write open recovers the WAL and, via `busy_timeout`,
/// waits the writer out — so the blob that is on disk the whole time stays
/// reachable. The captured cause of the strict-residency crash.
pub fn open_rw_shared_at(db_path: &std::path::Path) -> Option<Connection> {
    let conn = Connection::open_with_flags(
        db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_WRITE | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )
    .ok()?;
    let _ = conn.busy_timeout(std::time::Duration::from_secs(10));
    Some(conn)
}

#[cfg(test)]
pub fn open_cache_db_readonly(_workspace_root: Option<&str>, _lang: &str) -> Option<Connection> {
    None
}

/// A retained read connection: opened once through the caller's opener,
/// reused across calls, reopened when the DB file was unlinked/recreated
/// underneath it (inode change — `--clear-cache`, a row-format rebuild).
///
/// The ONE speller of retain-with-recheck: `ModuleIndex::with_rows_conn`
/// and the conclusion cache's loader both ride it. A per-call open costs
/// milliseconds (file open, WAL handshake, the CANTOPEN retry ladder)
/// against the microsecond query it serves — measured at 5.1 ms/call over
/// 70k conclusion-map loads, 360 s of accumulated open cost in one cold
/// `--check`, 13x the next-largest term in the run.
pub struct RetainedReader {
    cell: std::sync::Mutex<Option<(Connection, u64)>>,
}

impl Default for RetainedReader {
    fn default() -> Self {
        Self::new()
    }
}

impl RetainedReader {
    pub fn new() -> Self {
        RetainedReader { cell: std::sync::Mutex::new(None) }
    }

    fn db_ino(conn: &Connection) -> u64 {
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            return conn
                .path()
                .and_then(|p| std::fs::metadata(p).ok())
                .map(|m| m.ino())
                .unwrap_or(0);
        }
        #[cfg(not(unix))]
        {
            let _ = conn;
            0
        }
    }

    /// Drop the held connection — the next `with` reopens. For callers whose
    /// OPENER changed (a new workspace root), which the inode recheck cannot
    /// see: same file may exist at both paths.
    pub fn reset(&self) {
        let mut guard = self.cell.lock().unwrap_or_else(|p| p.into_inner());
        *guard = None;
    }

    /// Run `f` on the retained connection, opening through `opener` when
    /// none is held or the file moved underneath it. `None` when the open
    /// fails — a failure is NOT retained, so a DB created later is picked
    /// up on the next call.
    pub fn with<R>(
        &self,
        opener: impl FnOnce() -> Option<Connection>,
        f: impl FnOnce(&Connection) -> R,
    ) -> Option<R> {
        // Poison-proof: the Option is a pure cache — a panic in an earlier
        // holder must not permanently disable retrieval.
        let mut guard = self.cell.lock().unwrap_or_else(|p| p.into_inner());
        if let Some((conn, ino)) = guard.as_ref() {
            if Self::db_ino(conn) != *ino {
                *guard = None; // file unlinked/recreated — reopen below
            }
        }
        if guard.is_none() {
            *guard = opener().map(|c| {
                let ino = Self::db_ino(&c);
                (c, ino)
            });
        }
        let (conn, _) = guard.as_ref()?;
        Some(f(conn))
    }
}

#[cfg(test)]
mod retained_reader_tests {
    use super::RetainedReader;

    /// One open serves many calls; a recreated DB file (new inode) forces a
    /// reopen. The two behaviors this struct exists for, and the second is
    /// what keeps `--clear-cache` honest mid-session.
    #[test]
    fn opens_once_and_reopens_on_inode_change() {
        let dir = std::env::temp_dir().join(format!("rr_test_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let db = dir.join("t.db");
        super::Connection::open(&db).unwrap().execute_batch("CREATE TABLE t(x)").unwrap();

        let rr = RetainedReader::new();
        let opens = std::cell::Cell::new(0u32);
        let opener = || {
            opens.set(opens.get() + 1);
            super::Connection::open(&db).ok()
        };
        assert!(rr.with(opener, |_| ()).is_some());
        assert!(rr.with(opener, |_| ()).is_some());
        assert_eq!(opens.get(), 1, "the second call rides the retained connection");

        std::fs::remove_file(&db).unwrap();
        super::Connection::open(&db).unwrap().execute_batch("CREATE TABLE t(x)").unwrap();
        assert!(rr.with(opener, |_| ()).is_some());
        assert_eq!(opens.get(), 2, "a recreated file (new inode) must reopen");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A failed open is not retained: a DB that appears later is picked up.
    #[test]
    fn a_failed_open_is_retried_next_call() {
        let dir = std::env::temp_dir().join(format!("rr_late_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let db = dir.join("late.db");

        let rr = RetainedReader::new();
        assert!(rr.with(|| None, |_: &super::Connection| ()).is_none());
        super::Connection::open(&db).unwrap().execute_batch("CREATE TABLE t(x)").unwrap();
        assert!(
            rr.with(|| super::Connection::open(&db).ok(), |_| ()).is_some(),
            "the earlier failure must not be remembered as permanent"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
